version: '3'
services:
  api:
    build:
      context: ./alerta_api
    platform: linux/amd64
    ports:
      - 8080:8080
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://alerta:8l3rt8@db:5432/alerta
      - PLUGINS=acked_by,escalate,forwarder,timeout,reject,heartbeat,blackout,normalise
      - CORS_ORIGINS=*
    volumes:
      - ./alerta_api:/app
    networks:
      - net
    depends_on:
      - db
    restart: always
#  webui:
#    image: alerta/alerta-beta
##    build:
##      context: ./alerta_webui
#    ports:
#      - "80:80"
#    environment:
#      - VUE_APP_ALERTA_ENDPOINT=http://127.0.0.1:8080/
#    networks:
#      - net
#    restart: always
  db:
    image: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: alerta
      POSTGRES_USER: alerta
      POSTGRES_PASSWORD: 8l3rt8
    networks:
      - net
    restart: always
networks:
  net: {}

